version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: bi_postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: metabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres

  loader:
    image: python:3.10-slim
    container_name: gold_loader
    depends_on:
      - postgres
    volumes:
      - ./notebooks/data/gold:/data/gold   # map your gold parquet dir into loader
      - ./loader:/loader                   # put loader script here
    working_dir: /loader
    entrypoint: [ "bash", "-lc" ]
    command: >
      "pip install pandas pyarrow sqlalchemy psycopg2-binary && python /loader/load_gold_to_postgres.py"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: metabase
      PGPASSWORD: metabase
      PGDATABASE: metabase
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    hostname: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "7077:7077"
      - "8082:8080"
    volumes:
      - ./spark-data:/opt/spark/data
    restart: unless-stopped

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./spark-data:/opt/spark/data
    restart: unless-stopped

volumes:
  pgdata:
